# makefile for functions dir

declareFunc: declareFunc.c
	gcc -o declareFunc.exe declareFunc.c

withArgs: withArgs.c
	gcc -o withArg.exe withArgs.c

recursiveFuncs: recursiveFuncs.c
	gcc -o recursiveFuncs.exe recursiveFuncs.c