
arith: arith.c
	gcc -o arith.exe arith.c

conditionals: conditionals.c
	gcc -o conditionals.exe conditionals.c
	
measureSize: measureSize.c
	gcc -o measureSize.exe measureSize.c

# -lm to link the math.h lib definitions
compBitValues: compBitValues.c
	gcc -o compBitValues.exe compBitValues.c -lm 