
arith: arith.c
	gcc -o arith.exe arith.c

conditionals: conditionals.c
	gcc -o conditionals.exe conditionals.c
	
measureSize: measureSize.c
	gcc -o measureSize.exe measureSize.c

compBitValues: compBitValues.c
	gcc -o compBitValues.exe compBitValues.c