# make file for readingStrings dir

readStr: readStr.c
	gcc -Wall -o readStr.exe readStr.c

strCopy: strCopy.c
	gcc -Wall -o strCopy.exe strCopy.c

joinStr: joinStr.c
	gcc -Wall -o joinStr.exe joinStr.c

findSubStr: findSubStr.c
	gcc -Wall -o findSubStr.exe findSubStr.c

validateString: validateString.c
	gcc -Wall -o validateString.exe validateString.c