# logic expressions makefile

ifExperssions: ifExperssions.c
	gcc -o ifExperssions.exe ifExperssions.c

branching: branching.c
	gcc -o branching.exe branching.c

loopIteration: loopIteration.c
	gcc -o loopIteration.exe loopIteration.c

whileLoop: whileLoop.c
	gcc -o whileLoop.exe whileLoop.c