# make file for pointers dir

accessDataViaPtr: accessDataViaPtr.c
	gcc -o accessDataViaPtr.exe accessDataViaPtr.c

ptrArith: ptrArith.c
	gcc -o ptrArith.exe ptrArith.c

ptrToFunc: ptrToFunc.c
	gcc -o ptrToFunc.exe ptrToFunc.c