# make file for structs dir

groupingStructs: groupingStructs.c
	gcc -Wall -o groupingStructs.exe groupingStructs.c

typedStructs: typedStructs.c
	gcc -Wall -o typedStructs.exe typedStructs.c

grpStruct: grpStruct.c
	gcc -g3 -ggdb -Wall -o grpStruct.exe grpStruct.c