# make file for structs dir

groupingStructs: groupingStructs.c
	gcc -Wall -o groupingStructs.exe groupingStructs.c

typedStructs: typedStructs.c
	gcc -Wall -o typedStructs.exe typedStructs.c

grpStruct: grpStruct.c
	gcc -g3 -ggdb -Wall -o grpStruct.exe grpStruct.c

ptrStruct: ptrStruct.c
	gcc -g3 -ggdb -Wall -o ptrStruct.exe ptrStruct.c

ptrToStruct: ptrToStruct.c
	gcc -g3 -ggdb -Wall -o ptrToStruct.exe ptrToStruct.c

passStructToFunc: passStructToFunc.c
	gcc -g3 -ggdb -Wall -o passStructToFunc.exe passStructToFunc.c