

declareConst: declareConst.c
	gcc -o declareConst.exe declareConst.c

enumerateConst: enumerateConst.c
	gcc -o enumerateConst.exe enumerateConst.c

typeDef: typeDef.c
	gcc -o typeDef.exe typeDef.c

defConst: defConst.c
	gcc -o defConst.exe defConst.c